GET http://127.0.0.1:8000/api/categories
###
POST http://127.0.0.1:8000/api/transactions
Content-Type: application/json

{
    "user_id": 1,
    "category_id": 1,
    "type": "expense",
    "title": "Hamburguesa",
    "description": "Cena con amigos",
    "amount": 15.50,
    "transaction_date": "2026-07-06"
}
###
GET http://127.0.0.1:8000/api/transactions/1
###
PUT http://127.0.0.1:8000/api/transactions/1
Content-Type: application/json

{
  "category_id": 1,
  "type": "expense",
  "title": "Hamburguesa actualizada",
  "amount": 20,
  "transaction_date": "2026-07-06"
}
###
DELETE http://127.0.0.1:8000/api/transactions/1

###
GET http://127.0.0.1:8000/api/saving-goals

###
POST http://127.0.0.1:8000/api/saving-goals
Content-Type: application/json

{
  "user_id": 1,
  "title": "Viaje a Japón",
  "description": "Ahorro para viajar a Tokio",
  "target_amount": 5000,
  "current_amount": 500,
  "target_date": "2027-06-01",
  "priority": "high",
  "emoji": "🇯🇵"
}

###
GET http://127.0.0.1:8000/api/saving-goals/1

###
PUT http://127.0.0.1:8000/api/saving-goals/1
Content-Type: application/json

{
  "title": "Viaje a Japón 2027",
  "target_amount": 6000,
  "current_amount": 1000,
  "target_date": "2027-06-01",
  "priority": "high"
}

###
DELETE http://127.0.0.1:8000/api/saving-goals/1

###
PUT http://127.0.0.1:8000/api/coach-preferences/1
Content-Type: application/json

{
  "conversation_style": "motivador",
  "coach_background": "Estoy ahorrando para comprar mi primera vivienda."
}

###
GET http://127.0.0.1:8000/api/coach-preferences/1

###
GET http://127.0.0.1:8000/api/achievements

###
GET http://127.0.0.1:8000/api/users/1/achievements

###
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
  "nickname": "Sergio",
  "email": "sergio@example.com",
  "password": "Admin1234"
}

###
GET http://127.0.0.1:8000/api/user
Authorization: Bearer 1|ZSFg6tpD1UzDibqsqeEDDx6TEb0bx056CboUxBmif12e632e
Accept: application/json

###
POST http://127.0.0.1:8000/api/logout
Authorization: Bearer 1|ZSFg6tpD1UzDibqsqeEDDx6TEb0bx056CboUxBmif12e632e

###
POST http://127.0.0.1:8000/api/transactions
Authorization: Bearer 2|YmIYTMfKYfE0G6H9tbsXP8WLvmzEafbiWEzDobIEd6cf0bdf
Accept: application/json
Content-Type: application/json

{
  "category_id": 1,
  "type": "expense",
  "title": "Café",
  "description": "Café de la tarde",
  "amount": 2.50,
  "transaction_date": "2026-07-07"
}

###
POST http://127.0.0.1:8000/api/login
Accept: application/json
Content-Type: application/json

{
  "email": "sergio@example.com",
  "password": "Admin1234"
}

###
POST http://127.0.0.1:8000/api/saving-goals
Authorization: Bearer 2|YmIYTMfKYfE0G6H9tbsXP8WLvmzEafbiWEzDobIEd6cf0bdf
Accept: application/json
Content-Type: application/json

{
  "title": "Viaje a Japón",
  "description": "Viaje en 2027",
  "target_amount": 5000,
  "current_amount": 0,
  "target_date": "2027-06-01",
  "priority": "high",
  "emoji": "🇯🇵"
}